name: Build and Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag for the workflow"
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: "kohler/gifsicle"
          ref: ${{ github.event.inputs.tag }}

      - name: Windows Build
        if: matrix.os == 'windows-latest'
        shell: bash
        working-directory: ./src
        run: |
          nmake -f Makefile.w32
          mv gifsicle.exe ../gifsicle-windows-${{ github.event.inputs.tag }}.exe

      - name: Build
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          ./configure --disable-gifview --disable-gifdiff
          make
          mv gifsicle gifsicle-${{ runner.os }}-${{ github.event.inputs.tag }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gifsicle-${{ runner.os }}
          path: |
            gifsicle*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: "Release"
          files: "./artifacts/*"
          prerelease: true
